name: Branch Ownership Management

on:
  create:
    branches:
      - '*'  # Trigger on branch creation
  push:
    branches:
      - '*'  # Trigger on push events

permissions:
  contents: write  # Allow write access to repository contents

jobs:
  manage-branch-ownership:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Load or Create Branch Ownership Data
        id: load_data
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          OWNERS_FILE="branch_owners.json"

          # Create a JSON file if it doesn't exist
          if [ ! -f "$OWNERS_FILE" ]; then
            echo '{}' > "$OWNERS_FILE"
            echo "Created new owners file: $OWNERS_FILE"
          fi

          # Load existing ownership data
          BRANCH_OWNERS=$(cat "$OWNERS_FILE")
          
          # Check if the branch already has an owner
          BRANCH_CREATOR=$(echo "$BRANCH_OWNERS" | jq -r --arg BRANCH "$BRANCH_NAME" '.[$BRANCH]')
          
          if [ "$BRANCH_CREATOR" == "null" ]; then
            # Set the current actor as the owner of the new branch
            BRANCH_CREATOR="${GITHUB_ACTOR}"
            NEW_BRANCH_OWNERS=$(echo "$BRANCH_OWNERS" | jq --arg BRANCH "$BRANCH_NAME" --arg OWNER "$BRANCH_CREATOR" '. + {($BRANCH): $OWNER}')
            echo "$NEW_BRANCH_OWNERS" > "$OWNERS_FILE"
            echo "Set $BRANCH_NAME owner to $BRANCH_CREATOR"
          else
            echo "Branch already has an owner: $BRANCH_CREATOR"
          fi

          # Set output for later steps
          echo "branch_creator=$BRANCH_CREATOR" >> $GITHUB_ENV

      - name: Commit and Push Changes to Temporary Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create a temporary branch for updates
          git checkout -b update-owners-temp  
          
          # Fetch the latest changes from the remote
          git fetch origin update-owners || echo "No remote branch found, creating new one."
          
          # Merge any changes from the remote branch with unrelated histories allowed
          git merge origin/update-owners --allow-unrelated-histories || echo "No changes to merge."
          
          git add branch_owners.json
          git commit -m "Update branch ownership data for $BRANCH_NAME" || echo "No changes to commit."
          
          # Push to temporary branch
          git push origin update-owners-temp  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to Update Owners
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update Branch Ownership Data"
          body: "This PR updates the ownership data for branch $BRANCH_NAME."
          base: update-owners  # Target protected branch
          head: update-owners-temp  # Source temporary branch

      - name: Check Push Permissions
        if: github.event_name == 'push'
        run: |
          OWNER="${GITHUB_ACTOR}"
          BRANCH_CREATOR="${{ env.branch_creator }}"

          echo "Current Actor: $OWNER"
          echo "Branch Creator: $BRANCH_CREATOR"

          # Check if the branch creator is the same as the current actor
          if [[ "$BRANCH_CREATOR" != "$OWNER" ]]; then
            echo "You do not have permission to push to this branch."
            exit 1
          else
            echo "Permission granted to push to this branch."
          fi
